module.exports = {
    TOKEN_REQUIRED: "TOKEN IS REQUIRED TO CREATE NEW CLIENT",
    USERNAME_REQUIRED: "USERNAME IS REQUIRED TO CREATE NEW CLIENT",
    HOST_IS_REQUIRED: "HOST IS REQUIRED TO CREATE NEW CLIENT",
    BOARD_ID_IS_REQUIRED: "You cannot create a board without its id",
};